spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # (초기 개발 시 create, 이후 update)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080  # 포트 번호를 명시적으로 설정

logging:
  level:
    org.springframework.web: DEBUG  # Controller 관련 로그를 디버그 레벨로 출력
    org.springframework: DEBUG  # Spring 관련 전체 로그를 디버그 레벨로 출력
